In [11]:
import numpy as np
import pandas as pd


df=pd.read_table('amazon_alexa.tsv')

In [12]:
df.head()

,rating,date,variation,verified_reviews,feedback
0,5,31-Jul-18,Charcoal Fabric,Love my Echo!,1
1,5,31-Jul-18,Charcoal Fabric,Loved it!,1
2,4,31-Jul-18,Walnut Finish,"Sometimes while playing a game, you can answer...",1
3,5,31-Jul-18,Charcoal Fabric,I have had a lot of fun with this thing. My 4 ...,1
4,5,31-Jul-18,Charcoal Fabric,Music,1

In [13]:
df.isna().sum()
df.dropna(inplace=True)

In [14]:
df.duplicated().sum()

np.int64(715)

In [15]:
df['length']=df['verified_reviews'].apply(len)

In [16]:
df.head()

,rating,date,variation,verified_reviews,feedback,length
0,5,31-Jul-18,Charcoal Fabric,Love my Echo!,1,13
1,5,31-Jul-18,Charcoal Fabric,Loved it!,1,9
2,4,31-Jul-18,Walnut Finish,"Sometimes while playing a game, you can answer...",1,195
3,5,31-Jul-18,Charcoal Fabric,I have had a lot of fun with this thing. My 4 ...,1,172
4,5,31-Jul-18,Charcoal Fabric,Music,1,5

In [17]:
df['feedback'].value_counts()

feedback
1    2893
0     256
Name: count, dtype: int64

In [18]:
import nltk
from nltk.stem import PorterStemmer
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Hashir\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [19]:
stop_words = set(stopwords.words('english'))
ps = PorterStemmer()
import re

def preprocess(text):
    text=text.lower()
    text= re.sub(r'[^a-z\s]', '', text)
    tokens = text.split()
    tokens= [ps.stem(word) for word in tokens if word not in stop_words]
    return ' '.join(tokens)

df['cleaned']=df['verified_reviews'].apply(preprocess)

In [20]:
df.head()

,rating,date,variation,verified_reviews,feedback,length,cleaned
0,5,31-Jul-18,Charcoal Fabric,Love my Echo!,1,13,love echo
1,5,31-Jul-18,Charcoal Fabric,Loved it!,1,9,love
2,4,31-Jul-18,Walnut Finish,"Sometimes while playing a game, you can answer...",1,195,sometim play game answer question correctli al...
3,5,31-Jul-18,Charcoal Fabric,I have had a lot of fun with this thing. My 4 ...,1,172,lot fun thing yr old learn dinosaur control li...
4,5,31-Jul-18,Charcoal Fabric,Music,1,5,music

In [21]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer= TfidfVectorizer()
X= vectorizer.fit_transform(df['cleaned']).toarray()
y=df['feedback'].values

In [22]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
from sklearn.ensemble import RandomForestClassifier
model= RandomForestClassifier()
model.fit(X_train, y_train)
y_pred= model.predict(X_test)

In [23]:
model.score(X_test, y_test)

0.9222222222222223